ARG BASE=quay.io/shadowblue/main-nvidia:latest
FROM ${BASE}

COPY image/repos/ /etc/yum.repos.d/
COPY image/packages.txt /usr/share/machine/packages.txt
RUN sed 's/#.*//' /usr/share/machine/packages.txt | xargs dnf -y install && \
    dnf clean all && \
    rm -rf /var/lib/dnf /var/cache/libdnf5 /var/cache/ldconfig /var/log/dnf5.log /run/dnf

COPY image/files/ /
RUN jq '.transports.docker["ghcr.io/chelokot/machine"] = [{"type": "sigstoreSigned", "keyPath": "/etc/pki/containers/chelokot-machine.pub", "signedIdentity": {"type": "matchRepository"}}]' \
      /etc/containers/policy.json > /etc/containers/policy.json.new && \
    mv /etc/containers/policy.json.new /etc/containers/policy.json && \
    tee -a /etc/selinux/targeted/contexts/files/file_contexts.local /etc/selinux/targeted/active/file_contexts.local < /usr/share/machine/nix.fc > /dev/null && \
    systemctl enable nix.mount nix-daemon.socket && \
    systemctl --global enable podman.socket && \
    bootc container lint
